import Head from 'next/head'
import Sidebar from "../components/Sidebar";
import Table from "../components/Table";
import {Router} from "next/router";
import Top from "../components/Top";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Never Sleep</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/neverSleepIcon.png" />
            </Head>
            <div className='h-screen w-full flex bg-gradient-to-b from-blue-600 to-cyan-200'>
                <Sidebar/>
                <div className='h-screen w-full p-12 bg-blue-100 rounded-bl-[40px] rounded-tl-[40px]'>
                    <Top className='w-full'/>
                    <Table/>
                </div>
            </div>
        </div>
    )
}