import Head from 'next/head'
import Sidebar from "../components/Sidebar";
import Table from "../components/Table";
import Top from "../components/Top";
import React, {useState} from "react";

export default function Home() {
    const [searchValue, setSearchValue] = useState('')

    const onChangeSearch = (e)=> {
        setSearchValue(e)
    }

    return (
        <div>
            <Head>
                <title>Never Sleep</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/neverSleepIcon.png" />
            </Head>
            <div className='h-full w-full bg-blue-400 overflow-x-hidden'>
                <div className='h-full w-full gap-4 grid grid-cols-6'>
                    <Sidebar/>
                    <div className='col-span-5 w-full mx-4 space-y-4 h-full px-10 py-8 bg-blue-100 rounded-bl-[40px] rounded-tl-[40px]'>
                        <Top onChangeSearch={onChangeSearch}/>
                        <Table searchValue={searchValue}/>
                    </div>
                </div>
            </div>
        </div>
    )
}