import Head from 'next/head'
import Sidebar from "../components/Sidebar";
import Table from "../components/Table";
import Top from "../components/Top";
import React, {useState} from "react";

export default function Home() {
    const [searchValue, setSearchValue] = useState('')

    const onChangeSearch = (e)=> {
        setSearchValue(e)
    }

    return (
        <div>
            <Head>
                <title>Never Sleep</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/neverSleepIcon.png" />
            </Head>
            <div className='h-full w-full bg-blue-400'>
                <div className='overflow-x-hidden space-y-8 h-full w-full lg:space-y-0 lg:gap-4 lg:grid lg:grid-cols-6 lg:relative'>
                    <div className='lg:block lg:static'>
                        <Sidebar/>
                    </div>
                    <div className='w-full mx-4 space-y-4 h-full px-10 py-8 bg-blue-100 rounded-bl-[40px] rounded-tl-[40px] lg:relative lg:col-span-5'>
                        <div className='lg:static'>
                            <Top onChangeSearch={onChangeSearch}/>
                        </div>
                        <div className='lg:static'>
                            <Table searchValue={searchValue}/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}